# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c49cc18af9a19c74666111f3cea7b47ccbd9712727e7c6d4b154c611ce713053e0a86f2412eed60b20e44caaa621f5747fa85e93f8e5c26b45311c1640d8d541

test:
  secret_key_base: e84fdceac4258e4820dffd04a5786cf454a1819423d9b8db0ab8906e1c2d8686a63b9a05e87e124d0f6e65acfa49ec981eaa9b19b94a0bafce8d441d549be4f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
